# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - azure-devops-ci #temporary trigger name as feature branch for testing purposes

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: AWSShellScript@1
    displayName: AWS SAM build
    inputs:
      awsCredentials: "SDLC-AWS"
      regionName: "eu-west-2"
      scriptType: "filePath"
      filePath: "./build.sh"

  - task: AWSShellScript@1
    displayName: AWS SAM package
    inputs:
      awsCredentials: "SDLC-AWS"
      regionName: "eu-west-2"
      scriptType: "inline"
      inlineScript: |
        sam package --output-template-file packaged.yaml --s3-bucket lgss-continuous-integration

  - task: CopyFiles@2
    inputs:
      Contents: "packaged.yaml"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "package-output"
      publishLocation: "Container"
