AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SCDIP editor web service
Parameters:
  Stage:
    Type: String
    Default: dev
  Range:
    Type: String
    Default: '*'
Resources:
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName:
        Fn::Join:
        - ''
        - - Ref: Stage
          - -rekommend
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          AllowedOrigins:
          - '*'
          ExposedHeaders:
          - Date
          Id: rekommendCORSGetRule
          MaxAge: '3600'
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - PUT
          AllowedOrigins:
          - '*'
          ExposedHeaders:
          - Date
          Id: rekommendCORSPutRule
          MaxAge: '3600'
  MainTable:
    Type: AWS::Serverless::SimpleTable
    TableName:
      Fn::Join:
      - ''
      - - Ref: Stage
        - -rekommend
  EditorApiAlias:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.amazonaws.com/jerichotest/c2d9a03c9459c164163877da642cc6d8.template
      Parameters:
        MainTable:
          Ref: MainTable
        AttachmentsBucket:
          Ref: AttachmentsBucket
        Range:
          Ref: Range
        Stage:
          Ref: Stage
  PlayerApiAlias:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.amazonaws.com/jerichotest/38b95ddd837bf0341bb180519f6b3ceb.template
      Parameters:
        MainTable:
          Ref: MainTable
        AttachmentsBucket:
          Ref: AttachmentsBucket
        Range:
          Ref: Range
        Stage:
          Ref: Stage
Outputs:
  BucketName:
    Description: Name of the sample Amazon S3 bucket with CORS enabled.
    Value:
      Ref: AttachmentsBucket
  ApiURL:
    Description: Player API endpoint URL
    Value:
      Fn::Sub: https://${PlayerApiAlias.Outputs.ApiUrl}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
  EditorApiURL:
    Description: Editor API endpoint URL
    Value:
      Fn::Sub: https://${EditorApiAlias.Outputs.EditorApiURL}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
