version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rekommend"
s3_bucket = "rekommend-example"
s3_prefix = "rekommend"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""