name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-rekommend-api:
    runs-on: ubuntu-latest
    env:
      STACK_NAME: rekommend-dev
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2
      STAGE: Dev
      APPNAME: Rekommend-API

    steps:
      - uses: actions/checkout@v2

      - name: Build SAM package
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: sam build -t ./template.yaml

      - name: Package SAM package
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: sam package --output-template-file packaged.yaml --s3-bucket lgss-continuous-integration

      - name: Deploy SAM package
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: sam deploy --template-file packaged.yaml --stack-name $STACK_NAME --s3-bucket lgss-continuous-integration --capabilities CAPABILITY_IAM --region eu-west-2

      - name: Run tests
        run: |
          export REKOMMEND_API_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`ApiURL`].OutputValue' --output text)
          export REKOMMEND_EDITOR_API_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`EditorApiURL`].OutputValue' --output text)
          pip3 install unittest-xml-reporting
          python3 -m xmlrunner discover tests -o test-results
          python3 ./tests/post_test_results_to_slack.py
          
      - name: Post results to Slack
        run: |
          export SLACK_ENDPOINT=${{ secrets.SLACK_ENDPOINT }}
          python3 ./tests/post_test_results_to_slack.py
       
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        with:
          check_name: Test results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: test-results/*.xml
